name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - id: nodenv
      uses: nodenv/actions/node-version@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nodenv.outputs.node-version }}"
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier/

        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Run tests
      run: sbt test
